spring.application.name=Application-location-vehicule
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
#spring.datasource.url=jdbc:h2:mem:jpa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.h2.console.enabled=false

# Logs utiles pour voir les DDL/SQL au démarrage
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.tool.hbm2ddl=debug

# Encodage UTF?8 pour tous les fichiers de messages
spring.messages.encoding=UTF-8
spring.messages.basename=messages,validation
spring.messages.fallback-to-system-locale=false

server.port=9999

